name: Modify Latest Systemcore Images and Release

on:
  workflow_dispatch:

jobs:
  modify-latest-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Download Latest Systemcore LLUpdate Image
        id: llupdate
        uses: robinraju/release-downloader@v1
        with:
          repository: "limelightvision/systemcore-os-public"
          latest: true
          fileName: "*.llupdate"
      - name: Download Latest Full Systemcore Image
        id: osimage
        uses: robinraju/release-downloader@v1
        with:
          repository: "limelightvision/systemcore-os-public"
          latest: true
          fileName: "*.zip"
          extract: true
        
      - name: Setup
        run: |
          mkdir "$GITHUB_WORKSPACE/release"
          sudo chmod +x ./canlosetup.sh
          echo "# CANlosetup ${{ steps.osimage.outputs.release_name }}" > "$GITHUB_WORKSPACE/body.md"
          echo "Tag Name: ${{ steps.osimage.outputs.tag_name }}" >> "$GITHUB_WORKSPACE/body.md"
          echo "## CAN HATs" >> "$GITHUB_WORKSPACE/body.md"

      - name: Modify Images With CANlosetup
        run: |
          llupdate="${{ fromJson(steps.llupdate.outputs.downloaded_files)[0] }}"
          llupdatename="${llupdate##*/}"
          osimage="${{ fromJson(steps.osimage.outputs.downloaded_files)[0] }}"
          osimage="${osimage%%-*}.img"
          osimagename="${osimage##*/}"
          for canconf in ./config/*.txt; do
            [ -f "$canconf" ] || break
            can="${canconf%%.*}"
            echo "Modifying Systemcore Image for $can"
            echo "* $can" >> "$GITHUB_WORKSPACE/body.md"
            canllupdate="${llupdate%%.*}-${can}.llupdate"
            canosimage="${osimage%%}"
            cp "$llupdate" "$GITHUB_WORKSPACE/release/${can}-$llupdatename"
            cp "$osimage" "$GITHUB_WORKSPACE/release/${can}-$osimagename"
            sudo -E ./canlosetup.sh llupdate "$GITHUB_WORKSPACE/release/${can}-$llupdatename" "$can" 449
            sudo -E ./canlosetup.sh osimage "$GITHUB_WORKSPACE/release/${can}-$osimagename" "$can" 449
          done
      
      - name: Release Modified Images
        uses: ncipollo/release-action@v1
        with:
          artifacts: "$GITHUB_WORKSPACE/release/*"
          bodyFile: "$GITHUB_ACTIONS/body.md"
